project_id = "jvyklrivwjubuwjdmvfq"

[functions.test-rag]
verify_jwt = false

[functions.process-document]
verify_jwt = false

[functions.wa-webhook]
verify_jwt = false

[functions.wa-send-message]
verify_jwt = false
